default_language_version:
    python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint-travis
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [manual]
